// -----------------------------------------------------------------------------
// Copyright (C) Cambridge Silicon Radio plc 2013             http://www.csr.com
// Generated by ../../util/CommonParameters/DerivationEngine.py
// source v1.1, namespace com.csr.cps.2 on 2015-08-07 12:01:06 by wasbu_build
// from $Id: //depot/bg/ADK4.0-RELEASE/dsp/lib_private/music_manager/music_manager.xml#1 $
// last modifed with $Change: 2317643 $ by $Author: dh05 $ on $DateTime: 2015/07/10 11:14:28 $
// -----------------------------------------------------------------------------
#ifndef __MUSIC_MANAGER_CONFIG_H__
#define __MUSIC_MANAGER_CONFIG_H__

#define uses_WIRED_SUB_EQ_RAW_COEFS	0
#define uses_SPKR_EQ_RAW_COEFS     	0
#define uses_BASS_BOOST_RAW_COEFS  	0
#define uses_USER_EQ_RAW_COEFS     	0
#define uses_SPEAKER_CROSSOVER     	1
#define uses_SPKR_EQ               	1
#define uses_BASS_BOOST            	1
#define uses_USER_EQ               	1
#define uses_STEREO_ENHANCEMENT    	1
#define uses_DITHER                	1
#define uses_COMPANDER             	1
#define uses_VOLUME_CONTROL        	1
#define uses_SIGNAL_DETECTION      	1
#define uses_WIRED_SUB_COMPANDER   	1
#define uses_WIRED_SUB_EQ          	1

#define flag_uses_WIRED_SUB_EQ_RAW_COEFS	0x400000
#define flag_uses_SPKR_EQ_RAW_COEFS     	0x200000
#define flag_uses_BASS_BOOST_RAW_COEFS  	0x100000
#define flag_uses_USER_EQ_RAW_COEFS     	0x080000
#define flag_uses_SPEAKER_CROSSOVER     	0x040000
#define flag_uses_SPKR_EQ               	0x020000
#define flag_uses_BASS_BOOST            	0x010000
#define flag_uses_USER_EQ               	0x008000
#define flag_uses_STEREO_ENHANCEMENT    	0x002000
#define flag_uses_DITHER                	0x001000
#define flag_uses_COMPANDER             	0x000800
#define flag_uses_VOLUME_CONTROL        	0x000200
#define flag_uses_SIGNAL_DETECTION      	0x000100
#define flag_uses_WIRED_SUB_COMPANDER   	0x000080
#define flag_uses_WIRED_SUB_EQ          	0x000040


// Bit-mask flags to return in SPI status, which tells the Parameter Manager
// (Windows Realtime Tuning GUI) which modules are included in the build.  The
// mask is also written to the kap file so that the build configuration can be
// identified using a text editor.

#define MUSIC_MANAGER_CONFIG_FLAG	uses_WIRED_SUB_EQ_RAW_COEFS*flag_uses_WIRED_SUB_EQ_RAW_COEFS +  uses_SPKR_EQ_RAW_COEFS*flag_uses_SPKR_EQ_RAW_COEFS +  uses_BASS_BOOST_RAW_COEFS*flag_uses_BASS_BOOST_RAW_COEFS +  uses_USER_EQ_RAW_COEFS*flag_uses_USER_EQ_RAW_COEFS +  uses_SPEAKER_CROSSOVER*flag_uses_SPEAKER_CROSSOVER +  uses_SPKR_EQ*flag_uses_SPKR_EQ +  uses_BASS_BOOST*flag_uses_BASS_BOOST +  uses_USER_EQ*flag_uses_USER_EQ +  uses_STEREO_ENHANCEMENT*flag_uses_STEREO_ENHANCEMENT +  uses_DITHER*flag_uses_DITHER +  uses_COMPANDER*flag_uses_COMPANDER +  uses_VOLUME_CONTROL*flag_uses_VOLUME_CONTROL +  uses_SIGNAL_DETECTION*flag_uses_SIGNAL_DETECTION +  uses_WIRED_SUB_COMPANDER*flag_uses_WIRED_SUB_COMPANDER +  uses_WIRED_SUB_EQ*flag_uses_WIRED_SUB_EQ


#endif // __MUSIC_MANAGER_CONFIG_H__
