/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */

#include <panic.h>
#include <string.h>
#include "sink_gatt_db.h"

/* Static GATT database */
const uint16 gattDatabase[] = {
    /* 0001: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0002: Characteristic Declaration 2a05 */
    0x3005, 0x2003, 0x0005, 0x2a00,
    /* 0003:  */
    0xd000,
    /* 0004: Client Characteristic Configuration */
    0x6400,
    /* 0005: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0006: Characteristic Declaration 2a00 */
    0x3005, 0x0207, 0x0000, 0x2a00,
    /* 0007:  */
    0xd400,
    /* 0008: Characteristic Declaration 2a01 */
    0x3005, 0x0209, 0x0001, 0x2a00,
    /* 0009:  */
    0xd400,
    /* 000a: Primary Service fee7 */
    0x0002, 0xe7fe,
    /* 000b: Characteristic Declaration fec7 */
    0x3005, 0x080c, 0x00c7, 0xfe00,
    /* 000c: . */
    0xd401, 0x0000,
    /* 000d: Characteristic Declaration fec8 */
    0x3005, 0x320e, 0x00c8, 0xfe00,
    /* 000e: . */
    0xd401, 0x0000,
    /* 000f: Client Characteristic Configuration */
    0x6c00,
    /* 0010: Characteristic Declaration fec9 */
    0x3005, 0x0211, 0x00c9, 0xfe00,
    /* 0011: . */
    0xd401, 0x0000,
};

uint16 *GattGetDatabase(uint16 *len)
{
    uint16 *rc = PanicUnlessMalloc(sizeof(gattDatabase));
    *len = sizeof(gattDatabase);
    memmove(rc, gattDatabase, sizeof(gattDatabase));
    return rc;
}

uint16 GattGetDatabaseSize(void)
{
    return sizeof(gattDatabase);
}

/* End-of-File */
