/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from sink_gatt_db.db_
 */
#ifndef __SINK_GATT_DB_H
#define __SINK_GATT_DB_H

#include <csrtypes.h>

#define HANDLE_GATT_SERVICE             (0x0001)
#define HANDLE_GATT_SERVICE_END         (0x0004)
#define HANDLE_GATT_SERVICE_CHANGED     (0x0003)
#define HANDLE_GATT_SERVICE_CHANGED_CLIENT_CONFIG (0x0004)
#define HANDLE_GAP_SERVICE              (0x0005)
#define HANDLE_GAP_SERVICE_END          (0x0009)
#define HANDLE_DEVICE_NAME              (0x0007)
#define HANDLE_DEVICE_APPEARANCE        (0x0009)
#define HANDLE_WECHAT                   (0x000a)
#define HANDLE_WECHAT_END               (0xffff)
#define HANDLE_WRITE_CHARACTERISTIC     (0x000c)
#define HANDLE_INDICATE_CHARACTERISTIC  (0x000e)
#define HANDLE_WECHAR_CLIENT_CONFIG     (0x000f)
#define HANDLE_READ_CHARACTERISTIC      (0x0011)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
