.linefile 1 "user_eq.asm"
.linefile 1 "<command-line>"
.linefile 1 "user_eq.asm"
.linefile 11 "user_eq.asm"
.linefile 1 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/stack.h" 1
.linefile 12 "user_eq.asm" 2
.linefile 1 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/a2dp_low_latency_1mic_library_gen.h" 1
.linefile 12 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/a2dp_low_latency_1mic_library_gen.h"
.CONST $A2DP_LOW_LATENCY_1MIC_SYSID 0xE102;


.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.BASS_MANAGER_BYPASS 0x000800;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.SPKR_EQ_BYPASS 0x000400;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.EQFLAT 0x000200;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.USER_EQ_BYPASS 0x000100;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.BASS_BOOST_BYPASS 0x000080;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.SPATIAL_BYPASS 0x000040;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.COMPANDER_BYPASS 0x000020;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.DITHER_BYPASS 0x000010;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.USER_EQ_SELECT 0x000007;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.CNGENA 0x008000;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.RERENA 0x004000;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.SND_AGCBYP 0x001000;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.SNDOMSENA 0x000080;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.SIDETONEENA 0x000010;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.WNRBYP 0x000008;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.AECENA 0x000002;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.HDBYP 0x000004;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONFIG.BYPASS_AGCPERSIST 0x040000;


.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CUR_MODE_OFFSET 0;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.SYSCONTROL_OFFSET 1;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.FUNC_MIPS_OFFSET 2;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.DECODER_MIPS_OFFSET 3;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_PCMINL_OFFSET 4;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_PCMINR_OFFSET 5;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_DACL_OFFSET 6;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_DACR_OFFSET 7;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_SUB_OFFSET 8;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CUR_DACL_OFFSET 9;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.USER_EQ_BANK_OFFSET 10;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CONFIG_FLAG_OFFSET 11;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.DELAY 12;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_TYPE_OFFSET 13;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_FS_OFFSET 14;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_CHANNEL_MODE 15;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_STAT1 16;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_STAT2 17;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_STAT3 18;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_STAT4 19;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_STAT5 20;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.INTERFACE_TYPE 21;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.INPUT_RATE 22;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.OUTPUT_RATE 23;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CODEC_RATE 24;

.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CALL_STATE_OFFSET 25;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.SEC_STAT_OFFSET 26;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_ADC_OFFSET 27;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_SCO_OUT_OFFSET 28;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_MIPS_OFFSET 29;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_AUX_OFFSET 30;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.SIDETONE_GAIN 31;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.VOLUME 32;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.CONNSTAT 33;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.PEAK_SIDETONE 34;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.SND_AGC_SPEECH_LVL 35;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.SND_AGC_GAIN 36;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.AEC_COUPLING_OFFSET 37;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.WNR_PWR_LVL 38;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.DSP_VOL_FLAG 39;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.DSP_VOL 40;
.CONST $M.A2DP_LOW_LATENCY_1MIC.STATUS.BLOCK_SIZE 41;


.CONST $M.A2DP_LOW_LATENCY_1MIC.SYSMODE.STANDBY 0;
.CONST $M.A2DP_LOW_LATENCY_1MIC.SYSMODE.PASSTHRU 1;
.CONST $M.A2DP_LOW_LATENCY_1MIC.SYSMODE.FULLPROC 2;
.CONST $M.A2DP_LOW_LATENCY_1MIC.SYSMODE.LOWVOLUME 3;
.CONST $M.A2DP_LOW_LATENCY_1MIC.SYSMODE.MAX_MODES 4;


.CONST $M.A2DP_LOW_LATENCY_1MIC.CONTROL.DAC_OVERRIDE 0x8000;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONTROL.CALLSTATE_OVERRIDE 0x4000;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CONTROL.MODE_OVERRIDE 0x2000;


.CONST $M.A2DP_LOW_LATENCY_1MIC.INTERFACE.UNUSED 0;
.CONST $M.A2DP_LOW_LATENCY_1MIC.INTERFACE.ANALOG 1;
.CONST $M.A2DP_LOW_LATENCY_1MIC.INTERFACE.I2S 2;


.CONST $M.A2DP_LOW_LATENCY_1MIC.CALLST.MUTE 0;
.CONST $M.A2DP_LOW_LATENCY_1MIC.CALLST.CONNECTED 1;


.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CONFIG 0;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_NUM_BANDS 1;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_MASTER_GAIN 2;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE1_TYPE 3;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE1_FC 4;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE1_GAIN 5;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE1_Q 6;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE2_TYPE 7;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE2_FC 8;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE2_GAIN 9;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE2_Q 10;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE3_TYPE 11;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE3_FC 12;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE3_GAIN 13;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE3_Q 14;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE4_TYPE 15;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE4_FC 16;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE4_GAIN 17;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE4_Q 18;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE5_TYPE 19;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE5_FC 20;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE5_GAIN 21;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE5_Q 22;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE6_TYPE 23;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE6_FC 24;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE6_GAIN 25;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE6_Q 26;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE7_TYPE 27;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE7_FC 28;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE7_GAIN 29;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE7_Q 30;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE8_TYPE 31;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE8_FC 32;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE8_GAIN 33;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE8_Q 34;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE9_TYPE 35;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE9_FC 36;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE9_GAIN 37;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE9_Q 38;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE10_TYPE 39;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE10_FC 40;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE10_GAIN 41;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SPKR_EQ_STAGE10_Q 42;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_NUM_BANDS 43;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_MASTER_GAIN 44;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_TYPE 45;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_FC 46;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_GAIN 47;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BOOST_EQ_Q 48;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS 49;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_NUM_BANDS 50;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_MASTER_GAIN 51;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE1_TYPE 52;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE1_FC 53;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE1_GAIN 54;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE1_Q 55;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE2_TYPE 56;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE2_FC 57;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE2_GAIN 58;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE2_Q 59;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE3_TYPE 60;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE3_FC 61;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE3_GAIN 62;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE3_Q 63;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE4_TYPE 64;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE4_FC 65;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE4_GAIN 66;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE4_Q 67;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE5_TYPE 68;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE5_FC 69;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE5_GAIN 70;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ1_STAGE5_Q 71;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_NUM_BANDS 72;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_MAST_ERGAIN 73;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE1_TYPE 74;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE1_FC 75;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE1_GAIN 76;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE1_Q 77;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE2_TYPE 78;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE2_FC 79;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE2_GAIN 80;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE2_Q 81;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE3_TYPE 82;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE3_FC 83;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE3_GAIN 84;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE3_Q 85;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE4_TYPE 86;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE4_FC 87;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE4_GAIN 88;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE4_Q 89;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE5_TYPE 90;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE5_FC 91;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE5_GAIN 92;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ2_STAGE5_Q 93;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_NUM_BANDS 94;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_MASTER_GAIN 95;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE1_TYPE 96;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE1_FC 97;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE1_GAIN 98;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE1_Q 99;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE2_TYPE 100;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE2_FC 101;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE2_GAIN 102;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE2_Q 103;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE3_TYPE 104;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE3_FC 105;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE3_GAIN 106;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE3_Q 107;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE4_TYPE 108;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE4_FC 109;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE4_GAIN 110;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE4_Q 111;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE5_TYPE 112;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE5_FC 113;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE5_GAIN 114;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ3_STAGE5_Q 115;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_NUM_BANDS 116;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_MASTER_GAIN 117;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE1_TYPE 118;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE1_FC 119;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE1_GAIN 120;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE1_Q 121;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE2_TYPE 122;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE2_FC 123;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE2_GAIN 124;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE2_Q 125;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE3_TYPE 126;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE3_FC 127;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE3_GAIN 128;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE3_Q 129;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE4_TYPE 130;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE4_FC 131;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE4_GAIN 132;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE4_Q 133;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE5_TYPE 134;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE5_FC 135;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE5_GAIN 136;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ4_STAGE5_Q 137;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_NUM_BANDS 138;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_MASTER_GAIN 139;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE1_TYPE 140;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE1_FC 141;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE1_GAIN 142;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE1_Q 143;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE2_TYPE 144;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE2_FC 145;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE2_GAIN 146;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE2_Q 147;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE3_TYPE 148;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE3_FC 149;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE3_GAIN 150;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE3_Q 151;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE4_TYPE 152;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE4_FC 153;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE4_GAIN 154;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE4_Q 155;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE5_TYPE 156;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE5_FC 157;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE5_GAIN 158;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ5_STAGE5_Q 159;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_NUM_BANDS 160;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_MASTER_GAIN 161;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE1_TYPE 162;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE1_FC 163;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE1_GAIN 164;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE1_Q 165;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE2_TYPE 166;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE2_FC 167;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE2_GAIN 168;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE2_Q 169;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE3_TYPE 170;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE3_FC 171;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE3_GAIN 172;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE3_Q 173;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE4_TYPE 174;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE4_FC 175;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE4_GAIN 176;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE4_Q 177;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE5_TYPE 178;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE5_FC 179;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE5_GAIN 180;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ6_STAGE5_Q 181;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SDICONFIG 182;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DAC_GAIN_L 183;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DAC_GAIN_R 184;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TABLE_SIZE 185;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE0 186;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE1 187;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE2 188;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE3 189;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE4 190;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE5 191;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE6 192;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE7 193;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE8 194;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE9 195;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE10 196;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE11 197;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE12 198;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE13 199;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE14 200;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE15 201;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SB_TABLE16 202;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE0 203;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE1 204;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE2 205;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE3 206;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE4 207;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE5 208;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE6 209;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE7 210;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE8 211;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE9 212;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE10 213;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE11 214;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE12 215;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE13 216;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE14 217;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE15 218;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_SW_TABLE16 219;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE_SIZE 220;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE0 221;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE1 222;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE2 223;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE3 224;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE4 225;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE5 226;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SWAT_TRIM_TABLE6 227;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_CONFIG 228;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_A1 229;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_A2 230;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_A3 231;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_A4 232;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_A5 233;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_BASS_MANAGER_COEF_FREQ 234;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_S_EQ_B1 235;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_S_EQ_B0 236;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_S_EQ_A1 237;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP1_B2 238;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP1_B1 239;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP1_B0 240;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP2_B2 241;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP2_B1 242;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_L_AP2_B0 243;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP1_B2 244;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP1_B1 245;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP1_B0 246;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP2_B2 247;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP2_B1 248;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MELOD_EXPANSION_R_AP2_B0 249;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_THRESHOLD1 250;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_THRESHOLD1 251;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_THRESHOLD1 252;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_THRESHOLD1 253;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_EXPAND_RATIO1 254;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_LINEAR_RATIO1 255;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_COMPRESS_RATIO1 256;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_LIMIT_RATIO1 257;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_ATTACK_TC1 258;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_DECAY_TC1 259;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_ATTACK_TC1 260;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_DECAY_TC1 261;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_ATTACK_TC1 262;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_DECAY_TC1 263;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_ATTACK_TC1 264;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_DECAY_TC1 265;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MAKEUP_GAIN1 266;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_THRESHOLD2 267;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_THRESHOLD2 268;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_THRESHOLD2 269;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_THRESHOLD2 270;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_EXPAND_RATIO2 271;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_LINEAR_RATIO2 272;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_COMPRESS_RATIO2 273;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_LIMIT_RATIO2 274;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_ATTACK_TC2 275;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_EXPAND_DECAY_TC2 276;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_ATTACK_TC2 277;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LINEAR_DECAY_TC2 278;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_ATTACK_TC2 279;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_COMPRESS_DECAY_TC2 280;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_ATTACK_TC2 281;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LIMIT_DECAY_TC2 282;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_MAKEUP_GAIN2 283;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DITHER_NOISE_SHAPE 284;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC1_CONFIG 285;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC2_CONFIG 286;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC3_CONFIG 287;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC4_CONFIG 288;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC5_CONFIG 289;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC6_CONFIG 290;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC7_CONFIG 291;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC8_CONFIG 292;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC9_CONFIG 293;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CODEC10_CONFIG 294;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_HFK_CONFIG 295;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_HFK_OMS_AGGR 296;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ASR_OMS_AGGR 297;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_OMS_HARMONICITY 298;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_WNR_AGGR 299;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_WNR_POWER_THRES 300;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_WNR_HOLD 301;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CNG_Q 302;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CNG_SHAPE 303;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DTC_AGGR 304;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ENABLE_AEC_REUSE 305;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ADCGAIN 306;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_CONFIG 307;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_GAIN_EXP 308;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_GAIN_MANT 309;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE1_B2 310;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE1_B1 311;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE1_B0 312;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE1_A2 313;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE1_A1 314;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE2_B2 315;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE2_B1 316;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE2_B0 317;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE2_A2 318;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE2_A1 319;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE3_B2 320;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE3_B1 321;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE3_B0 322;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE3_A2 323;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE3_A1 324;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE4_B2 325;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE4_B1 326;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE4_B0 327;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE4_A2 328;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE4_A1 329;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE5_B2 330;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE5_B1 331;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE5_B0 332;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE5_A2 333;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_STAGE5_A1 334;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_SCALE1 335;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_SCALE2 336;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_SCALE3 337;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_SCALE4 338;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_PEQ_SCALE5 339;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_LVMODE_THRES 340;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE 341;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE1 342;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE2 343;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE3 344;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE4 345;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE5 346;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE6 347;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE7 348;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE8 349;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE9 350;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE10 351;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE11 352;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE12 353;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE13 354;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE14 355;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_INV_DAC_GAIN_TABLE15 356;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_CLIP_POINT 357;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_ADJUST_LIMIT 358;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_STF_SWITCH 359;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_STF_NOISE_LOW_THRES 360;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_STF_NOISE_HIGH_THRES 361;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_STF_GAIN_EXP 362;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_STF_GAIN_MANTISSA 363;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_CONFIG 364;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_GAIN_EXP 365;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_GAIN_MANT 366;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE1_B2 367;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE1_B1 368;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE1_B0 369;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE1_A2 370;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE1_A1 371;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE2_B2 372;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE2_B1 373;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE2_B0 374;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE2_A2 375;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE2_A1 376;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE3_B2 377;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE3_B1 378;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE3_B0 379;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE3_A2 380;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_STAGE3_A1 381;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_SCALE1 382;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_SCALE2 383;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ST_PEQ_SCALE3 384;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SNDGAIN_MANTISSA 385;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SNDGAIN_EXPONENT 386;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_PT_SNDGAIN_MANTISSA 387;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_PT_SNDGAIN_EXPONENT 388;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_REF_DELAY 389;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_ADCGAIN_SSR 390;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_ATTACK_TC 391;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_DECAY_TC 392;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_ENVELOPE_TC 393;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_INIT_FRAME_THRESH 394;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_RATIO 395;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_MIN_SIGNAL 396;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_MIN_MAX_ENVELOPE 397;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_DELTA_THRESHOLD 398;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_VAD_COUNT_THRESHOLD 399;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_G_INITIAL 400;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_TARGET 401;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_ATTACK_TC 402;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_DECAY_TC 403;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_A_90_PK 404;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_D_90_PK 405;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_G_MAX 406;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_START_COMP 407;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_COMP 408;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_INP_THRESH 409;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_SP_ATTACK 410;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_AD_THRESH1 411;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_AD_THRESH2 412;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_G_MIN 413;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_SND_AGC_ECHO_HOLD_TIME 414;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_ATTACK_TC 415;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_DECAY_TC 416;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_ENVELOPE_TC 417;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_INIT_FRAME_THRESH 418;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_RATIO 419;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_MIN_SIGNAL 420;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_MIN_MAX_ENVELOPE 421;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_DELTA_THRESHOLD 422;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_RCV_VAD_COUNT_THRESHOLD 423;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_HD_THRESH_GAIN 424;

.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_0 425;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_1 426;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_2 427;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_3 428;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_4 429;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_5 430;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_6 431;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_7 432;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_8 433;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_DSP_USER_9 434;
.CONST $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.STRUCT_SIZE 435;
.linefile 13 "user_eq.asm" 2
.linefile 1 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/a2dp_low_latency_1mic_config.h" 1
.linefile 14 "user_eq.asm" 2
.linefile 1 "user_eq.h" 1
.linefile 11 "user_eq.h"
.linefile 1 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/cbuffer.h" 1
.linefile 11 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/cbuffer.h"
   .CONST $cbuffer.SIZE_FIELD 0;
   .CONST $cbuffer.READ_ADDR_FIELD 1;
   .CONST $cbuffer.WRITE_ADDR_FIELD 2;




      .CONST $cbuffer.STRUC_SIZE 3;




 .CONST $frmbuffer.CBUFFER_PTR_FIELD 0;
 .CONST $frmbuffer.FRAME_PTR_FIELD 1;
 .CONST $frmbuffer.FRAME_SIZE_FIELD 2;
 .CONST $frmbuffer.STRUC_SIZE 3;
.linefile 42 "C:/ADK4.0.0/kalimba/lib_sets/sdk/include/cbuffer.h"
      .CONST $cbuffer.NUM_PORTS 12;
      .CONST $cbuffer.WRITE_PORT_OFFSET 0x00000C;
      .CONST $cbuffer.PORT_NUMBER_MASK 0x00000F;
      .CONST $cbuffer.TOTAL_PORT_NUMBER_MASK 0x00001F;
      .CONST $cbuffer.TOTAL_CONTINUOUS_PORTS 8;







   .CONST $cbuffer.MMU_PAGE_SIZE 64;


   .CONST $cbuffer.READ_PORT_MASK 0x800000;
   .CONST $cbuffer.WRITE_PORT_MASK $cbuffer.READ_PORT_MASK + $cbuffer.WRITE_PORT_OFFSET;




   .CONST $cbuffer.FORCE_ENDIAN_MASK 0x300000;
   .CONST $cbuffer.FORCE_ENDIAN_SHIFT_AMOUNT -21;
   .CONST $cbuffer.FORCE_LITTLE_ENDIAN 0x100000;
   .CONST $cbuffer.FORCE_BIG_ENDIAN 0x300000;


   .CONST $cbuffer.FORCE_SIGN_EXTEND_MASK 0x0C0000;
   .CONST $cbuffer.FORCE_SIGN_EXTEND_SHIFT_AMOUNT -19;
   .CONST $cbuffer.FORCE_SIGN_EXTEND 0x040000;
   .CONST $cbuffer.FORCE_NO_SIGN_EXTEND 0x0C0000;


   .CONST $cbuffer.FORCE_BITWIDTH_MASK 0x038000;
   .CONST $cbuffer.FORCE_BITWIDTH_SHIFT_AMOUNT -16;
   .CONST $cbuffer.FORCE_8BIT_WORD 0x008000;
   .CONST $cbuffer.FORCE_16BIT_WORD 0x018000;
   .CONST $cbuffer.FORCE_24BIT_WORD 0x028000;
   .CONST $cbuffer.FORCE_32BIT_WORD 0x038000;


   .CONST $cbuffer.FORCE_SATURATE_MASK 0x006000;
   .CONST $cbuffer.FORCE_SATURATE_SHIFT_AMOUNT -14;
   .CONST $cbuffer.FORCE_NO_SATURATE 0x002000;
   .CONST $cbuffer.FORCE_SATURATE 0x006000;


   .CONST $cbuffer.FORCE_PADDING_MASK 0x001C00;
   .CONST $cbuffer.FORCE_PADDING_SHIFT_AMOUNT -11;
   .CONST $cbuffer.FORCE_PADDING_NONE 0x000400;
   .CONST $cbuffer.FORCE_PADDING_LS_BYTE 0x000C00;
   .CONST $cbuffer.FORCE_PADDING_MS_BYTE 0x001400;


   .CONST $cbuffer.FORCE_PCM_AUDIO $cbuffer.FORCE_LITTLE_ENDIAN +
                                                      $cbuffer.FORCE_SIGN_EXTEND +
                                                      $cbuffer.FORCE_SATURATE;
   .CONST $cbuffer.FORCE_24B_PCM_AUDIO $cbuffer.FORCE_LITTLE_ENDIAN +
                                                      $cbuffer.FORCE_32BIT_WORD +
                                                      $cbuffer.FORCE_PADDING_MS_BYTE +
                                                      $cbuffer.FORCE_NO_SATURATE;

   .CONST $cbuffer.FORCE_16BIT_DATA_STREAM $cbuffer.FORCE_BIG_ENDIAN +
                                                      $cbuffer.FORCE_NO_SIGN_EXTEND +
                                                      $cbuffer.FORCE_NO_SATURATE;
.linefile 12 "user_eq.h" 2



    .const $user_eq.DEFINITION_TABLE_MAX_NUM_BANKS 0;
    .const $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS 1;
    .const $user_eq.DEFINITION_TABLE_LEFT_DM_PTR 2;
    .const $user_eq.DEFINITION_TABLE_RIGHT_DM_PTR 3;
    .const $user_eq.DEFINITION_TABLE_COEFS_A_PTR 4;
    .const $user_eq.DEFINITION_TABLE_COEFS_B_PTR 5;

    .const $user_eq.DEFINITION_TABLE_SIZE 6;



    .const $user_eq.num_bands 0;
    .const $user_eq.pre_gain 1;



    .const $user_eq.filter_type.bypass 0;

    .const $user_eq.filter_type.lp_1 1;
    .const $user_eq.filter_type.hp_1 2;
    .const $user_eq.filter_type.ap_1 3;

    .const $user_eq.filter_type.ls_1 4;
    .const $user_eq.filter_type.hs_1 5;
    .const $user_eq.filter_type.tlt_1 6;

    .const $user_eq.filter_type.lp_2 7;
    .const $user_eq.filter_type.hp_2 8;
    .const $user_eq.filter_type.ap_2 9;

    .const $user_eq.filter_type.ls_2 10;
    .const $user_eq.filter_type.hs_2 11;
    .const $user_eq.filter_type.tlt_2 12;

    .const $user_eq.filter_type.peq 13;



    .const $user_eq.freq_param_scale 3;
    .const $user_eq.gain_param_scale 60;
    .const $user_eq.q_param_scale 12;


    .const $user_eq.gain_lo_gain_limit -2160;
    .const $user_eq.gain_hi_gain_limit 720;


    .const $user_eq.hi_nyquist_freq_limit 0.453515;






    .const $user_eq.xp_1_lo_freq_limit 1;
    .const $user_eq.xp_1_hi_freq_limit 60000;


    .const $user_eq.xp_2_lo_freq_limit 120;
    .const $user_eq.xp_2_hi_freq_limit 60000;
    .const $user_eq.xp_2_lo_q_limit 0x0400;
    .const $user_eq.xp_2_hi_q_limit 0x2000;


    .const $user_eq.shelf_1_lo_freq_limit 60;
    .const $user_eq.shelf_1_hi_freq_limit 60000;
    .const $user_eq.shelf_1_lo_gain_limit -720;
    .const $user_eq.shelf_1_hi_gain_limit 720;


    .const $user_eq.shelf_2_lo_freq_limit 120;
    .const $user_eq.shelf_2_hi_freq_limit 60000;
    .const $user_eq.shelf_2_lo_gain_limit -720;
    .const $user_eq.shelf_2_hi_gain_limit 720;
    .const $user_eq.shelf_2_lo_q_limit 0x0400;
    .const $user_eq.shelf_2_hi_q_limit 0x2000;


    .const $user_eq.peq_lo_freq_limit 60;
    .const $user_eq.peq_hi_freq_limit 60000;
    .const $user_eq.peq_lo_gain_limit -2160;
    .const $user_eq.peq_hi_gain_limit 720;
    .const $user_eq.peq_lo_q_limit 0x0400;
    .const $user_eq.peq_hi_q_limit 0x8000;



    .const $user_eq.GAIAMSG.SET_USER_PARAM 0x121a;
    .const $user_eq.GAIAMSG.GET_USER_PARAM 0x129a;
    .const $user_eq.GAIAMSG.SET_USER_GROUP_PARAM 0x121b;
    .const $user_eq.GAIAMSG.GET_USER_GROUP_PARAM 0x129b;

    .const $user_eq.GAIAMSG.SET_USER_PARAM_RESP 0x321a;
    .const $user_eq.GAIAMSG.GET_USER_PARAM_RESP 0x329a;
    .const $user_eq.GAIAMSG.SET_USER_GROUP_PARAM_RESP 0x321b;
    .const $user_eq.GAIAMSG.GET_USER_GROUP_PARAM_RESP 0x329b;
.linefile 15 "user_eq.asm" 2


.module $user_eq;
.CODESEGMENT PM;

.DATASEGMENT DM;


userEqInitialize:







    push rLink;


    r2 = M[&$M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_CONFIG];
    r2 = r2 and $M.A2DP_LOW_LATENCY_1MIC.CONFIG.USER_EQ_SELECT;
    r1 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANKS];
    r2 = min r1;

    r0 = m[r7 + $user_eq.DEFINITION_TABLE_COEFS_A_PTR];
    r1 = m[r7 + $user_eq.DEFINITION_TABLE_COEFS_B_PTR];

    r8 = r8 + r2;
    r8 = m[r8];

    r3 = r8 + 1;
 if nz jump calcBankCoefs.jump_entry;





    r2 = r2 - 1;
    r3 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANKS];
    r1 = M[$M.set_codec_rate.current_codec_sampling_rate];
    null = r1 - 48000;
    if z r2 = r2 + r3;
    r3 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS];
    r3 = r3 * 6 (int);
    r3 = r3 + 3;
    r3 = r3 * r2 (int);
    r0 = r0 + r3;



    pushm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    popm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_RIGHT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    jump $pop_rLink_and_rts;



eqInitialize:







    push rLink;



    r0 = m[r7 + $user_eq.DEFINITION_TABLE_COEFS_A_PTR];
    r1 = m[r7 + $user_eq.DEFINITION_TABLE_COEFS_B_PTR];

 r8 = m[r8];
 if nz jump calcBankCoefs.jump_entry;




    r2 = M[$M.set_codec_rate.current_codec_sampling_rate];
    null = r2 - 48000;
    if z r0 = r1;



    pushm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    popm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_RIGHT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    jump $pop_rLink_and_rts;



calcBankCoefs.call_entry:
    push rLink;
calcBankCoefs.jump_entry:
.linefile 134 "user_eq.asm"
    r2 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    r2 = m[r2 + $audio_proc.peq.PARAM_PTR_FIELD];
    null = r2 - r0;
    if eq r0 = r1;





    pushm <r0,r7>;




    i0 = r8;
    i1 = r0;

    null = r8;
    if nz jump calcBankCoefs.NotNullBank;

        r0 = 0;
        m[i1,1] = r0;
        r0 = 0x000001;
        m[i1,1] = r0;
        r0 = 0x400000;
        m[i1,1] = r0;
        jump calcBankCoefs.switchToNewCoefs;

    calcBankCoefs.NotNullBank:


    r0 = m[i0,1];
    m[i1,1] = r0;
    push r0;


    call calcPreGain.call_entry;


    r0 = i1;
    r1 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS];
    r1 = r1 * 5 (int);
    r0 = r0 + r1;
    i2 = r0;

    calcBandLoop:
        pop r0;
        r0 = r0 - 1;
        if neg jump calcBankCoefs.switchToNewCoefs;
        push r0;

        pushm <i0,i1,i2>;
        call coefCalcBiquadBand.call_entry;
        popm <r0,r1,r2>;
        r0 = r0 + 4;
        i0 = r0;
        r1 = r1 + 5;
        i1 = r1;
        r2 = r2 + 1;
        i2 = r2;

        jump calcBandLoop;

    calcBankCoefs.switchToNewCoefs:


    popm <r0,r7>;

    pushm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    popm <r0,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_RIGHT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r0;
    call $audio_proc.hq_peq.initialize;

    jump $pop_rLink_and_rts;



calcBandCoefs:
.linefile 227 "user_eq.asm"
    push rLink;

    r4 = r0;
    r0 = r0 and 0x00fff0;
    call calcParamAddrOffset;
    r8 = r0 + r3;





    r6 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    r6 = m[r6 + $audio_proc.peq.PARAM_PTR_FIELD];
    null = r6 - r1;
    if eq jump calcBandCoefsB;


    r3 = r2;
    r2 = r1;
    jump calcBandCoefsAorB;

    calcBandCoefsB:
    r3 = r1;


    calcBandCoefsAorB:





    i0 = r3;
    i1 = r2;


    r10 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS];
    r10 = r10 * 6 (int);
    r10 = r10 + 3;


    do copyCurrentCoefsLoop;
        r0 = m[i0,1];
        m[i1,1] = r0;
    copyCurrentCoefsLoop:

    i0 = r8;


    r0 = r4;
    call calcCoefAddrOffset;
    r8 = r0 + r2;
    i1 = r8;
    r8 = r1 + r2;
    i2 = r8;






    pushm <r2,r7>;


    r0 = r4;
    call coefCalc;


    popm <r2,r7>;
    pushm <r2,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_LEFT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r2;
    call $audio_proc.hq_peq.initialize;

    popm <r2,r7>;
    r7 = m[r7 + $user_eq.DEFINITION_TABLE_RIGHT_DM_PTR];
    m[r7 + $audio_proc.peq.PARAM_PTR_FIELD] = r2;
    call $audio_proc.hq_peq.initialize;

    jump $pop_rLink_and_rts;



calcParamAddrOffset:
.linefile 319 "user_eq.asm"
    pushm <r1,r2,r3>;

    r1 = r0 and 0x000f00;
    r1 = r1 ashift -8;
    r2 = r0 and 0x0000f0;
    r2 = r2 ashift -4;
    r3 = r0 and 0x00000f;


    r0 = r3;
    null = r1 - 0;
    if eq jump completedParamAddrCalculation;


    r1 = r1 - 1;
    r0 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS];
    r0 = r0 * 4 (int);
    r0 = r0 + 2;
    r1 = r1 * r0 (int);
    r0 = r1 + r3;
    r0 = r0 + 1;
    null = r2 - 0;
    if eq jump completedParamAddrCalculation;


    r2 = r2 - 1;
    r2 = r2 * 4 (int);
    r0 = r0 + r2;
    r0 = r0 + 2;

    completedParamAddrCalculation:

    popm <r1,r2,r3>;

    rts;



calcCoefAddrOffset:
.linefile 368 "user_eq.asm"
    pushm <r2,r3>;


    r2 = r0 and 0x0000f0;
    r2 = r2 ashift -4;
    r3 = r0 and 0x00000f;


    r0 = r3;
    null = r2 - 0;
    if eq jump completedCoefAddrCalculation;


    r2 = r2 - 1;
    r0 = m[r7 + $user_eq.DEFINITION_TABLE_MAX_NUM_BANDS];
    r0 = r0 * 5 (int);
    r0 = r0 + 3;
    r1 = r2 + r0;
    r0 = r2 * 5 (int);
    r0 = r0 + 3;

    completedCoefAddrCalculation:

    popm <r2,r3>;

    rts;



coefCalc:
.linefile 408 "user_eq.asm"
    push rLink;


    r2 = r0 and 0x0000f0;
    r2 = r2 ashift -4;
    if nz jump coefCalcBiquadBand.jump_entry;



    r0 = r0 and 0x00000f;
    null = r0 - $user_eq.num_bands;
    if eq jump calcNumBands.jump_entry;

    r2 = m[i0,1];
    null = r0 - $user_eq.pre_gain;
    if eq jump calcPreGain.jump_entry;

    pop rLink;
    rts;



coefCalcBiquadBand.call_entry:
    push rLink;
coefCalcBiquadBand.jump_entry:
.linefile 442 "user_eq.asm"
    r0 = m[i0,1];

    null = r0 - $user_eq.filter_type.bypass;
    if eq jump calcBypass.jump_entry;



    r7 = $kal_filter_coef_lib.calc_low_pass_1st;
    null = r0 - $user_eq.filter_type.lp_1;
    if eq jump calcXP1.jump_entry;

    r7 = $kal_filter_coef_lib.calc_high_pass_1st;
    null = r0 - $user_eq.filter_type.hp_1;
    if eq jump calcXP1.jump_entry;

    r7 = $kal_filter_coef_lib.calc_all_pass_1st;
    null = r0 - $user_eq.filter_type.ap_1;
    if eq jump calcXP1.jump_entry;



    r7 = $kal_filter_coef_lib.calc_low_pass_2nd;
    null = r0 - $user_eq.filter_type.lp_2;
    if eq jump calcXP2.jump_entry;

    r7 = $kal_filter_coef_lib.calc_high_pass_2nd;
    null = r0 - $user_eq.filter_type.hp_2;
    if eq jump calcXP2.jump_entry;

    r7 = $kal_filter_coef_lib.calc_all_pass_2nd;
    null = r0 - $user_eq.filter_type.ap_2;
    if eq jump calcXP2.jump_entry;



    r7 = $kal_filter_coef_lib.calc_low_shelf_1st;
    null = r0 - $user_eq.filter_type.ls_1;
    if eq jump calcShelf1.jump_entry;

    r7 = $kal_filter_coef_lib.calc_high_shelf_1st;
    null = r0 - $user_eq.filter_type.hs_1;
    if eq jump calcShelf1.jump_entry;

    r7 = $kal_filter_coef_lib.calc_tilt_1st;
    null = r0 - $user_eq.filter_type.tlt_1;
    if eq jump calcShelf1.jump_entry;



    r7 = $kal_filter_coef_lib.calc_low_shelf_2nd;
    null = r0 - $user_eq.filter_type.ls_2;
    if eq jump calcShelf2.jump_entry;

    r7 = $kal_filter_coef_lib.calc_high_shelf_2nd;
    null = r0 - $user_eq.filter_type.hs_2;
    if eq jump calcShelf2.jump_entry;

    r7 = $kal_filter_coef_lib.calc_tilt_2nd;
    null = r0 - $user_eq.filter_type.tlt_2;
    if eq jump calcShelf2.jump_entry;



    null = r0 - $user_eq.filter_type.peq;
    if eq jump calcPEQ.jump_entry;

    coefCalcInvalid:





    pop rLink;
    rts;



calcNumBands.call_entry:

    push rLink;

calcNumBands.jump_entry:

    r0 = m[i0,1];
    m[i1,1] = r0;

    pop rLink;
    rts;



calcPreGain.call_entry:

    push rLink;

calcPreGain.jump_entry:


    r0 = $user_eq.gain_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];
    r0 = r0 lshift 8;
    r0 = r0 ashift -8;

    r1 = $user_eq.gain_lo_gain_limit;
    r0 = max r1;
    r1 = $user_eq.gain_hi_gain_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;

    call $kal_filter_coef_lib.__db2lin.call_entry;



    r0 = r0 and 0x0000ff;
    r0 = r0 - 127;
    r1 = r1 lshift -1;

    m[i1,1] = r0;
    m[i1,1] = r1;

    pop rLink;
    rts;



calcBypass.jump_entry:



    sp = sp + 6;

    call $kal_filter_coef_lib.calc_bypass;

    jump pop_biquad_coefs_and_rts;



calcXP1.jump_entry:



    sp = sp + 6;

    r0 = $user_eq.freq_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];

    r5 = 48000;
    r4 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r4 = r5;
 r5 = $user_eq.hi_nyquist_freq_limit;
 r4 = r4 * r5;
    r4 = r4 * 3 (int);
 null = r0 - r4;
 if gt jump substituteBypassFilter.jump_entry;
    r1 = $user_eq.xp_1_lo_freq_limit;
    r0 = max r1;
    r1 = $user_eq.xp_1_hi_freq_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;

    r1 = 48000;
    r0 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r0 = r1;
    call $kal_float_lib.int_to_float;
    pushm <r0,r1>;

    call r7;

    jump pop_biquad_coefs_and_rts;



calcXP2.jump_entry:



    sp = sp + 6;


    r0 = $user_eq.freq_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];

    r5 = 48000;
    r4 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r4 = r5;
 r5 = $user_eq.hi_nyquist_freq_limit;
 r4 = r4 * r5;
    r4 = r4 * 3 (int);
 null = r0 - r4;
 if gt jump substituteBypassFilter.jump_entry;
    r1 = $user_eq.xp_2_lo_freq_limit;
    r0 = max r1;
    r1 = $user_eq.xp_2_hi_freq_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;

    r0 = m[i0,1];


    r0 = m[i0,1];

    r1 = $user_eq.xp_2_lo_q_limit;
    r0 = max r1;
    r1 = $user_eq.xp_2_hi_q_limit;
    r0 = min r1;
    r1 = $user_eq.q_param_scale;
    call $kal_float_lib.q_to_float;
    pushm <r0,r1>;

    r1 = 48000;
    r0 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r0 = r1;
    call $kal_float_lib.int_to_float;
    pushm <r0,r1>;

    call r7;

    jump pop_biquad_coefs_and_rts;



calcShelf1.jump_entry:



    sp = sp + 6;


    r0 = $user_eq.freq_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];

    r5 = 48000;
    r4 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r4 = r5;
 r5 = $user_eq.hi_nyquist_freq_limit;
 r4 = r4 * r5;
    r4 = r4 * 3 (int);
 null = r0 - r4;
 if gt jump substituteBypassFilter.jump_entry;
    r1 = $user_eq.shelf_1_lo_freq_limit;
    r0 = max r1;
    r1 = $user_eq.shelf_1_hi_freq_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;


    r0 = $user_eq.gain_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];
    r0 = r0 lshift 8;
    r0 = r0 ashift -8;

    r1 = $user_eq.shelf_1_lo_gain_limit;
    r0 = max r1;
    r1 = $user_eq.shelf_1_hi_gain_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;

    r1 = 48000;
    r0 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r0 = r1;
    call $kal_float_lib.int_to_float;
    pushm <r0,r1>;

    call r7;

    jump pop_biquad_coefs_and_rts;



calcShelf2.jump_entry:



    sp = sp + 6;


    r0 = $user_eq.freq_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];

    r5 = 48000;
    r4 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r4 = r5;
 r5 = $user_eq.hi_nyquist_freq_limit;
 r4 = r4 * r5;
    r4 = r4 * 3 (int);
 null = r0 - r4;
 if gt jump substituteBypassFilter.jump_entry;
    r1 = $user_eq.shelf_2_lo_freq_limit;
    r0 = max r1;
    r1 = $user_eq.shelf_2_hi_freq_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;


    r0 = $user_eq.gain_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];
    r0 = r0 lshift 8;
    r0 = r0 ashift -8;

    r1 = $user_eq.shelf_2_lo_gain_limit;
    r0 = max r1;
    r1 = $user_eq.shelf_2_hi_gain_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;


    r0 = m[i0,1];

    r1 = $user_eq.shelf_2_lo_q_limit;
    r0 = max r1;
    r1 = $user_eq.shelf_2_hi_q_limit;
    r0 = min r1;
    r1 = $user_eq.q_param_scale;
    call $kal_float_lib.q_to_float;
    pushm <r0,r1>;

    r1 = 48000;
    r0 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r0 = r1;
    call $kal_float_lib.int_to_float;
    pushm <r0,r1>;

    call r7;

    jump pop_biquad_coefs_and_rts;



calcPEQ.jump_entry:



    sp = sp + 6;


    r0 = $user_eq.freq_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];

    r5 = 48000;
    r4 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r4 = r5;
 r5 = $user_eq.hi_nyquist_freq_limit;
 r4 = r4 * r5;
    r4 = r4 * 3 (int);
 null = r0 - r4;
 if gt jump substituteBypassFilter.jump_entry;
    r1 = $user_eq.peq_lo_freq_limit;
    r0 = max r1;
    r1 = $user_eq.peq_hi_freq_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;


    r0 = $user_eq.gain_param_scale;
    call $kal_float_lib.int_to_float;
    r2 = r0;
    r3 = r1;
    r0 = m[i0,1];
    r0 = r0 lshift 8;
    r0 = r0 ashift -8;

    r1 = $user_eq.peq_lo_gain_limit;
    r0 = max r1;
    r1 = $user_eq.peq_hi_gain_limit;
    r0 = min r1;
    call $kal_float_lib.int_to_float;
    call $kal_float_lib.div;
    pushm <r0,r1>;


    r0 = m[i0,1];

    r1 = $user_eq.peq_lo_q_limit;
    r0 = max r1;
    r1 = $user_eq.peq_hi_q_limit;
    r0 = min r1;
    r1 = $user_eq.q_param_scale;
    call $kal_float_lib.q_to_float;
    pushm <r0,r1>;

    r1 = 48000;
    r0 = m[$M.set_codec_rate.current_codec_sampling_rate];
    if z r0 = r1;
    call $kal_float_lib.int_to_float;
    pushm <r0,r1>;

    call $kal_filter_coef_lib.calc_peq;

    jump pop_biquad_coefs_and_rts;



substituteBypassFilter.jump_entry:


    call $kal_filter_coef_lib.calc_bypass;

    jump pop_biquad_coefs_and_rts;



pop_biquad_coefs_and_rts:


    pop r0;
    m[i1,1] = r0;
    pop r0;
    m[i1,1] = r0;
    pop r0;
    m[i1,1] = r0;
    pop r0;
    m[i1,1] = r0;
    pop r0;
    m[i1,1] = r0;
    pop r0;
    m[i2,1] = r0;

    pop rLink;
    rts;


.endmodule;




.module $M.a2dp_low_latency_msg.SetUserEqParamMsg;
.linefile 923 "user_eq.asm"
    .datasegment dm ;
    .codesegment pm ;

func:

    push rLink ;

    r0 = r1;
    r7 = &$M.system_config.data.UserEqDefnTable;
    call $user_eq.calcParamAddrOffset;
    r0 = r0 + ($M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS);

    r2 = r2 and 0x00ffff;
    m[r0] = r2;


    null = r3 - 0;
    if eq jump $pop_rLink_and_rts ;

    r0 = r1;
    r1 = &$M.system_config.data.UserEqCoefsA;
    r2 = &$M.system_config.data.UserEqCoefsB;
    r3 = ($M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS);
    call $user_eq.calcBandCoefs;

    jump $pop_rLink_and_rts ;

.endmodule ;



.module $M.a2dp_low_latency_msg.GetUserEqParamMsg;
.linefile 972 "user_eq.asm"
    .datasegment dm ;
    .codesegment pm ;

func:

    push rLink ;

    r3 = r1;

    r0 = r1;
    r7 = &$M.system_config.data.UserEqDefnTable;
    call $user_eq.calcParamAddrOffset;
    r0 = r0 + ($M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS);

    r4 = m[r0];
    r5 = 0;
    r6 = 0;
    r2 = $user_eq.GAIAMSG.GET_USER_PARAM_RESP;
    call $message.send_short;

    jump $pop_rLink_and_rts ;

.endmodule ;



.module $M.a2dp_low_latency_msg.SetUserEqGroupParamMsg;
.linefile 1012 "user_eq.asm"
    .datasegment dm ;
    .codesegment pm ;

func:

    push rLink ;

    i0 = r3;
    r1 = m[i0,1];
    r7 = &$M.system_config.data.UserEqDefnTable;
    r10 = r1;
    do SetParamsLoop;
        r0 = m[i0,1];
        call $user_eq.calcParamAddrOffset;
        r0 = r0 + ($M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS);
        r1 = m[i0,1];
        r1 = r1 and 0x00ffff;
        m[r0] = r1;
    SetParamsLoop:



    jump $pop_rLink_and_rts ;

.endmodule ;



.module $M.a2dp_low_latency_msg.GetUserEqGroupParamMsg;
.linefile 1056 "user_eq.asm"
    .datasegment dm ;
    .codesegment pm ;

func:

    push rLink ;

    i0 = r3;
    r1 = m[i0,1];
    r7 = &$M.system_config.data.UserEqDefnTable;
    r10 = r1;
    do GetParamsLoop;
        r0 = m[i0,1];
        call $user_eq.calcParamAddrOffset;
        r0 = r0 + ($M.CVC.data.CurParams + $M.A2DP_LOW_LATENCY_1MIC.PARAMETERS.OFFSET_USER_EQ_NUM_BANKS);
        r0 = m[r0];
        m[i0,1] = r0;
    GetParamsLoop:

    r5 = r3;
    r4 = r2;
    r3 = $user_eq.GAIAMSG.GET_USER_GROUP_PARAM_RESP;
    call $message.send_long;

    jump $pop_rLink_and_rts ;


.endmodule;
