/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from gatt_wechat_server/gatt_wechat_server_db.dbi_
 */
#ifndef __GATT_WECHAT_SERVER_DB_H
#define __GATT_WECHAT_SERVER_DB_H

#include <csrtypes.h>

#define HANDLE_WECHAT                   (0x0001)
#define HANDLE_WECHAT_END               (0xffff)
#define HANDLE_WRITE_CHARACTERISTIC     (0x0003)
#define HANDLE_INDICATE_CHARACTERISTIC  (0x0005)
#define HANDLE_WECHAR_CLIENT_CONFIG     (0x0006)
#define HANDLE_READ_CHARACTERISTIC      (0x0008)

uint16 *GattGetDatabase(uint16 *len);
uint16 GattGetDatabaseSize(void);

#endif

/* End-of-File */
